- name: Test for APP_SETTINGS env var
  shell: cat /etc/environment | grep "export APP_SETTINGS=" | wc -l
  register: test_app_settings_grep

- name: Replace existing APP_SETTINGS environment variable
  lineinfile:
    state: present
    path: /etc/environment
    regexp: "^export APP_SETTINGS=(.*)$"
    backrefs: yes
    line: "export APP_SETTINGS={{ app_settings }}"
  when: test_app_settings_grep.stdout != "0"

- name: Set the APP_SETTINGS environment variable
  lineinfile:
    state: present
    path: /etc/environment
    line: "export APP_SETTINGS={{ app_settings }}"
  when: test_app_settings_grep.stdout == "0"

- name: Add SECRET_KEY environment variable
  lineinfile:
    state: present
    path: /etc/environment
    line: "export SECRET_KEY={{ flask_secret_key }}"
